//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCHEANGE_PARA.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXCHEANGE_PARA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap american_flag_2043285_960_720 {
            get {
                object obj = ResourceManager.GetObject("american-flag-2043285_960_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap arkaplanb {
            get {
                object obj = ResourceManager.GetObject("arkaplanb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap arkaplang {
            get {
                object obj = ResourceManager.GetObject("arkaplang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Balance_Scale {
            get {
                object obj = ResourceManager.GetObject("Balance Scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Calculator {
            get {
                object obj = ResourceManager.GetObject("Calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Cash {
            get {
                object obj = ResourceManager.GetObject("Cash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Cash_Register1 {
            get {
                object obj = ResourceManager.GetObject("Cash Register1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Closed_Eye {
            get {
                object obj = ResourceManager.GetObject("Closed Eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Copybook {
            get {
                object obj = ResourceManager.GetObject("Copybook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Exchange {
            get {
                object obj = ResourceManager.GetObject("Exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Eye {
            get {
                object obj = ResourceManager.GetObject("Eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Flag_of_Europe_svg {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Europe.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Fraud1 {
            get {
                object obj = ResourceManager.GetObject("Fraud1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Left_Handed {
            get {
                object obj = ResourceManager.GetObject("Left Handed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Lock1 {
            get {
                object obj = ResourceManager.GetObject("Lock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap New_Copym {
            get {
                object obj = ResourceManager.GetObject("New Copym", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Night {
            get {
                object obj = ResourceManager.GetObject("Night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Safe {
            get {
                object obj = ResourceManager.GetObject("Safe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Scales {
            get {
                object obj = ResourceManager.GetObject("Scales", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Scales3 {
            get {
                object obj = ResourceManager.GetObject("Scales3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Spiral_Bound_Booklet {
            get {
                object obj = ResourceManager.GetObject("Spiral Bound Booklet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap User4 {
            get {
                object obj = ResourceManager.GetObject("User4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap User5 {
            get {
                object obj = ResourceManager.GetObject("User5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
